<?php
/* Glass Factory Tables - 25-02-2023 Ramiz Girach*/
define("TBL_CATEGORY", "tbl_category");
define("TBL_COLOR", "tbl_color");
define("TBL_CUSTOMER", "tbl_customer");
define("TBL_FABRICATION", "tbl_fabrication");
define("TBL_INVOICE", "tbl_invoice");
define("TBL_INVOICE_DTL", "tbl_invoice_dtl");
define("TBL_PRODUCT_TYPE", "tbl_product_type");
define("TBL_PURCHASE", "tbl_purchase");
define("TBL_QUOTATION", "tbl_quotation");
define("TBL_SIZE", "tbl_size");
define("TBL_STOCK", "tbl_stock");
define("TBL_SUPPILER_STOCK", "tbl_suppiler_stock");
define("TBL_SUPPLIER", "tbl_supplier");
define("TBL_PRODUCT_GROUP", "tbl_product_group");
define("TBL_PURCHASE_DTL", "tbl_purchase_dtl");
define("TBL_QUOTATION_DTL", "tbl_quotation_dtl");
define("TBL_EXPENSES", "tbl_expenses");
define("TBL_NAV_MENU", "nav_menu");
define("TBL_M_ROLE", "tbl_m_role");
define("TBL_STATUS", "tbl_status");


/* Tables */

define("TBL_APP_CITY", "app_city");
define("TBL_APP_STATE", "tbl_app_state");
define("TBL_EVENT", "tbl_event");
define("TBL_EVENT_CAR", "tbl_event_cars");
define("TBL_CMS", "tbl_cms");
define("TBL_CONTACT_US", "tbl_contact_us");
define("TBL_HOMECMS", "tbl_home_cms");
define("TBL_HOME_FEATURE", "tbl_home_feature");
define("TBL_M_BODYTYPE", "tbl_m_bodytype");
define("TBL_M_CARAGE", "tbl_m_car_age");
define("TBL_M_FUELTYPE", "tbl_m_fueltype");
define("TBL_M_KMRANGE", "tbl_m_km_range");
define("TBL_M_MAKE", "tbl_m_make");
define("TBL_M_MODEL", "tbl_m_model");
define("TBL_M_OWNER", "tbl_m_owner");
define("TBL_M_PRICERANGE", "tbl_m_price_range");
define("TBL_M_STATEREG", "tbl_m_state_reg");
define("TBL_M_TRANSMISSION", "tbl_m_transmission");
define("TBL_T_CARS", "tbl_t_cars");
define("TBL_T_CARIMAGES", "tbl_t_car_images");
define("TBL_VEHICLE_TYPE", "tbl_vehicle_type");
define("TBL_USERS", "users");
define("TBL_USER_INFOMATION", "tbl_user_information");
define("TBL_APP_FEEDBACK", "tbl_app_feedback");
define("TBL_APP_NEWSLETTER", "tbl_app_newsletter");
define("TBL_BID", "tbl_bid");
define("TBL_BID_STATUS", "tbl_bid_status");
define("TBL_USER_ACCOUNT", "tbl_user_account");
define("TBL_USER_INFORMATION", "tbl_user_information");
define("TBL_USER_MEMBERSHIP", "tbl_user_membership");
define("TBL_USER_WALLET", "tbl_user_wallet");
define("TBL_WISHLIST", "tbl_wishlist");
define("TBL_APP_ABOUSTUS", "tbl_app_aboutus");
define("TBL_TFAQ", "tbl_t_faq");
//define("TBL_USER_TRANSACTION", "tbl_user_transaction");
define("TBL_TRANSACTION_LOG", "tbl_transaction_log");
define("TBL_CLIENT", "tbl_client");
define("TBL_CLIENT_COMMISSION", "tbl_client_commision");
define("TBL_RSD", "tbl_rsd");
define("TBL_SALES_REPRESENTATIVE", "tbl_sales_representative");
define("TBL_USER_WITHDRAW_REQ", "tbl_user_windraw_req");
define("TBL_SETTING", "tbl_setting");
define("TBL_USER_VALUATION_DOWNLOAD", "tbl_user_valuation_download");
define("TBL_T_CAR_NOC", "tbl_t_car_noc");
define("TBL_REFERAL_CODE", "tbl_referal_code");
define("TBL_USER_BUYING_LIMIT", "tbl_user_buying_limit");
define("TBL_USER_PAN_VERIFY_DATA", "tbl_user_pan_verify_data");
define("TBL_USER_NOTIFICATION", "tbl_user_notification");
define("TBL_USER_REFERAL_INCENTIVE", "tbl_user_referal_incentive");
define("TBL_CITY", "tbl_city");
define("TBL_STATE", "tbl_state");
define("TBL_PINCODE", "tbl_pincode");
define("TBL_AUCTION_JOURNEY", "tbl_auction_journey");
define("TBL_BID_HISTORY", "tbl_bid_history");
define("TBL_BID_FOLLOWUP_HISTORY", "tbl_bid_followup_history");
define("TBL_EMPLOYEES", " tbl_employees");
define("TBL_SMS_TEMPLATES", " tbl_sms_templates");
define("TBL_USER_SMS_HISTORY", " tbl_user_sms_history");
define("TBL_USER_MEMBERSHIP_HISTORY", "tbl_user_membership_history");
define("TBL_USER_EVENT_TERMS_ACCEPT", "tbl_user_event_terms_accept");
define("TBL_USER_BUYER_FEES_HISTORY", "tbl_user_buyer_fees_history");
define("TBL_USER_RSD_HISTORY_LOG", "tbl_user_rsd_history_log");
define("TBL_USER_REGISTRATION_TERMS_ACCEPT_HISTORY", "tbl_user_registration_terms_accept_history");
define("TBL_USER_STATE", "tbl_user_state");
define("TBL_EMPLOYEE_STATE", "tbl_employee_states");
define("TBL_EMPLOYEE_VEHICLE_TYPES", "tbl_employee_vehicle_types");
define("TBL_SUBSCRIPTION_PLAN", "tbl_subscription_plan");

define("TBL_YARD", "tbl_yard");
define("TBL_YARD_LOCATION", "tbl_yard_location");
define("TBL_YARD_PAN_VERIFY_DATA", "tbl_yard_pan_verify_data");
define("TBL_MARKETING_KIT", "tbl_marketing_kit");
define("TBL_BANK_INVOICE_MAKER", "tbl_bank_invoice_maker");
define("TBL_BANK_INVOICE_MAKER_DTL", "tbl_bank_invoice_maker_dtl");
define("TBL_TEMP_BANK_INVOICE_MAKER", "tbl_temp_bank_invoice_maker");
define("TBL_TEMP_BANK_INVOICE_MAKER_DTL", "tbl_temp_bank_invoice_maker_dtl");
define("TBL_BANK_INVOICE_MAKER_HISTROY", "tbl_bank_invoice_maker_history");
?>